input: path/to/regional_annotation.json
image_filename: 123.svs
output_folder: path/to/folder/to/write/annotations
annotation_name: StarDist Segmentations with Lymphocyte Classifications
line_colors:
  Other: rgb(0, 255, 0)
  Lymphocyte: rgb(255, 0, 0)
fill_colors:
  Other: rgba(0, 255, 0, 0)
  Lymphocyte: rgba(255, 0, 0, 0)
