input:
  Tumor: /path/to/Tumor.png
  Fat: /path/to/Fat.png
  Necrosis: /path/to/Necrosis.png
  Stroma: /path/to/Stroma.png
image_filename: 123.svs
output_folder: path/to/folder/to/write/annotations
annotation_name: Full Res Tile-Based Pixel Classifier Inference
line_colors:
  Stroma: rgb(0,191,255)
  Tumor: rgb(0,255,0)
  Fat: rgb(255,255,0)
  Necrosis: rgb(255,0,0)
fill_colors:
  Stroma: rgba(0,191,255,100)
  Tumor: rgba(0,255,0,100)
  Fat: rgba(255,255,0,100)
  Necrosis: rgba(255,0,0,100)
